8 14
lecture from Backup pour vendeurs
0 vendeurs lus, timestamp from 99999999999999 to 0

lecture from web pour vendeurs :minval=99999999999999,maxval=0,inf=8,sup=14 
6 vendeurs lus, timestamp from 8 to 14

1 2033
lecture from Backup pour clients
0 clients lus, timestamp from 99999999999999 to 0

lecture from web pour clients :minval=99999999999999,maxval=0,inf=1,sup=2033 
2033 clients lus, timestamp from 1 to 2033

1 1669
lecture from Backup pour produits
0 produits lus, timestamp from 99999999999999 to 0

lecture from web pour produits :minval=99999999999999,maxval=0,inf=1,sup=1669 
1669 produits lus, timestamp from 1 to 1669

1 71
lecture from Backup pour fournisseurs
0 fournisseurs lus, timestamp from 99999999999999 to 0

lecture from web pour fournisseurs :minval=99999999999999,maxval=0,inf=1,sup=71 
71 fournisseurs lus, timestamp from 1 to 71

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python24\lib\lib-tk\Tkinter.py", line 1345, in __call__
    return self.func(*args)
  File "<stdin>", line 1728, in route
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python24\lib\lib-tk\Tkinter.py", line 1345, in __call__
    return self.func(*args)
  File "<stdin>", line 1728, in route
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python24\lib\lib-tk\Tkinter.py", line 1345, in __call__
    return self.func(*args)
  File "<stdin>", line 1728, in route
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python24\lib\lib-tk\Tkinter.py", line 1345, in __call__
    return self.func(*args)
  File "<stdin>", line 1728, in route
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python24\lib\lib-tk\Tkinter.py", line 1345, in __call__
    return self.func(*args)
  File "<stdin>", line 1728, in route
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python24\lib\lib-tk\Tkinter.py", line 1345, in __call__
    return self.func(*args)
  File "<stdin>", line 1728, in route
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python24\lib\lib-tk\Tkinter.py", line 1345, in __call__
    return self.func(*args)
  File "<stdin>", line 1728, in route
IndexError: string index out of range
